Algoritmo "sequencia_impares"

// Leia um valor inteiro X. Em seguida mostre os ímpares
// de 1 até X, um valor por linha, inclusive o X, se for o caso.

// 12/07/2023

Var

   x, i : inteiro

Inicio

      escreval("Vou mostrar todos os números impares até o digitado!")
      escreva("Digite um número: ")
      leia(x)


      para i de 1 até x faca
           se i % 2 <> 0 então
           escrevaL(i)
           fimse
      fimpara
           

Fimalgoritmo